version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: cd giraffe && yarn run lint
      - run: cd giraffe && yarn run typecheck
      - run: cd giraffe && yarn run test --collectCoverage
      - run: cd giraffe && yarn run build
      - run: cd stories && yarn run lint
      - run: cd stories && yarn run typecheck
      - store_artifacts:
          path: coverage
      # See: https://github.com/influxdata/giraffe/issues/129
      # - run:
      #     name: chromatic
      #     command: |
      #       cd stories
      #       # See https://docs.chromaticqa.com/setup_ci
      #       if [ "${CIRCLE_BRANCH}" != "master" ];
      #       then
      #         yarn run chromatic
      #       else \
      #         yarn run chromatic -- --auto-accept-changes
      #       fi
