version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: cd giraffe && yarn run lint
      - run: cd giraffe && yarn run typecheck
      - run: cd giraffe && yarn run test --collectCoverage
      - run: cd giraffe && yarn run build
      - run: cd stories && yarn run lint
      - run: cd stories && yarn run typecheck
      - store_artifacts:
          path: giraffe/coverage

  chromatic-deployment: 
    docker:
      - image: circleci/node:12
    working_directory: ~/repo
    steps:
      - checkout
      # todo cache
      - run: yarn install
      - run: 
          name: chromatic
          command: |
            cd stories
            if [ "${CIRCLE_BRANCH}" != "master" ];
            then
              yarn run chromatic --project-token=${CHROMATIC_PROJECT_TOKEN}
            else \
              yarn run chromatic --project-token=${CHROMATIC_PROJECT_TOKEN} --auto-accept-changes
            fi
